name: build-test
on:
  push:    
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: make test